### ISSUE TITLE
Getting distorted meshes

### ISSUE THREAD

**Issue by kelteseth** [perliedman/osmwave#1]
Hi! First I want to thank you for this project for being a nice learning experience and example!

My goal is to write a simple OSM viewer in Qt (qt3d) but I only get strange geometry.  I attached Friedrichshafen.osm and the corresponding N47E009.hgt.

``` cpp

void Util::getMapTest()
{
    std::string def = "+proj=longlat"; // Not sure if this is right...
    std::string stream = osmwave::osm_to_obj("D:\\Backup\\Code\\Qt\\QOsmium\\Data\\Friedrichshafen.osm", 
                                                                      "D:\\Backup\\Code\\Qt\\QOsmium\\Data\\",
                                                                       &def);

    QString path = QCoreApplication::applicationDirPath() + "/out.obj";
    QFile file { path };
    file.open(QIODevice::WriteOnly | QIODevice::Text);
    QTextStream out(&file);
    out << QString::fromStdString(stream);

    file.close();
    emit mapLoaded(path);
}
```

[out.zip](https://github.com/perliedman/osmwave/files/5074052/out.zip)
[Data.zip](https://github.com/perliedman/osmwave/files/5074056/Data.zip)

When I open the obj file in blender it looks like this: 
![grafik](https://user-images.githubusercontent.com/1071536/90240243-25f41500-de29-11ea-999e-fb8f9ff8b4a3.png)

Thanks for your time! 😊

**Comment by perliedman** [comment]
Hi there!

Sad to say, I have not used this project in years, and it's far from impossible it has severe bugs.

Having said that, from just looking at that screenshot, might it actually be that its just a very zoomed out view of the data, also rotated 90 degrees?

From looking at the output, it seems the projection used was lonlat, which is ok for some use cases, but generally I'd recommend you set it up to use the UTM zone in question for your data, or maybe even better try https://github.com/perliedman/local-proj, which I actually wrote explicitly to find a local projection suitable for 3d models: if you use this utility, the model will be centered around 0,0,0.

**Comment by kelteseth** [comment]
Thanks for your reply!
Simply changing it to tmerc did the trick :)
`    std::string def = "+proj=tmerc  +ellps=WGS84 +datum=WGS84 +no_defs";`

![grafik](https://user-images.githubusercontent.com/1071536/90387040-bf1f6780-e085-11ea-8445-6908a340aee3.png)

Edit: Also inspired by your local-proj project with the 0,0,0 fix adding the lon and lat did help with the offset
` std::string def = "+proj=tmerc +lat_0=47.66051 +lon_0=9.48842 +k=1.000000 +x_0=0 +y_0=0   +ellps=WGS84 +datum=WGS84 +no_defs";`

Cheers!
